---
- hosts: all
  become: true
  tasks:
    - name: Update repository index (Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Install Apache (Debian/Ubuntu)
      apt:
        name: apache2
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Add PHP support for Apache (Debian/Ubuntu)
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Update repository index (AlmaLinux/CentOS)
      dnf:
        update_cache: yes
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - name: Install Apache (AlmaLinux/CentOS)
      dnf:
        name: httpd
        state: latest
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - name: Add PHP support for Apache (AlmaLinux/CentOS)
      dnf:
        name: php
        state: latest
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - name: Ensure firewalld is installed (AlmaLinux/CentOS)
      dnf:
        name: firewalld
        state: present
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - name: Ensure firewalld is running (AlmaLinux/CentOS)
      service:
        name: firewalld
        state: started
        enabled: true
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - name: Allow HTTP service through firewall (AlmaLinux/CentOS)
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: true
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - name: Start and enable Apache (httpd) (AlmaLinux/CentOS)
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution in ["AlmaLinux", "CentOS"]
    
    - name: Verify Apache is listening on port 80
      shell: ss -lntp | grep :80
      register: apache_port
      changed_when: false
      when: ansible_distribution in ["AlmaLinux", "CentOS"]

    - debug: 
        var: apache_port.stdout
