- name: k3s health check (read-only)
  hosts: k3s
  gather_facts: false
  become: true

  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml

  tasks:
    - name: Check kubectl exists
      ansible.builtin.command: kubectl version --client=true
      register: kubectl_client
      changed_when: false
      failed_when: kubectl_client.rc != 0

    - name: Get nodes
      ansible.builtin.command: kubectl --kubeconfig {{ kubeconfig }} get nodes -o wide
      register: nodes
      changed_when: false

    - name: Get AWX namespace pods
      ansible.builtin.command: kubectl --kubeconfig {{ kubeconfig }} -n awx get pods -o wide
      register: awx_pods
      changed_when: false

    - name: Get last 30 cluster events (all namespaces)
      ansible.builtin.shell: |
        kubectl --kubeconfig {{ kubeconfig }} get events -A --sort-by=.metadata.creationTimestamp | tail -n 30
      register: events_tail
      changed_when: false

    - name: Show nodes
      ansible.builtin.debug:
        msg: "{{ nodes.stdout_lines }}"

    - name: Show awx pods
      ansible.builtin.debug:
        msg: "{{ awx_pods.stdout_lines }}"

    - name: Show recent events tail
      ansible.builtin.debug:
        msg: "{{ events_tail.stdout_lines }}"
