---
- hosts: all
  become: true
  tasks:
  
  - name: Safety guard - refuse to run unless molecule_env=test
    ansible.builtin.assert:
    that:
      - (molecule_env | default('')) == 'test'
    fail_msg: "Refusing to run: this run is not marked as test."
    tags: [always]

  - name: update repository index (AlmaLinux)
    tags: always
    dnf:
       update_cache: yes
    changed_when: false
    when: ansible_distribution == "AlmaLinux"
 
  - name: update repository index (Ubuntu)
    tags: always
    apt:
       update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  roles:
      - base

- hosts: all
  become: true
  roles:
     - users

- hosts: workstations
  become: true
  roles:
     - workstations
 
- hosts: web_servers
  become: true
  roles:
     - web_servers
 
- hosts: db_servers
  become: true
  roles:
     - db_servers
 
- hosts: file_servers
  become: true
  roles:
     - file_servers

- hosts: solr_servers
  become: true
  roles:
    - { role: solr, tags: ["solr"] }
